CREATE DATABASE mural;

\c mural;

CREATE SCHEMA mural;

CREATE TABLE mural.user (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    creation_date TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE mural.message (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    text VARCHAR(255) NOT NULL,
    user_id INT NOT NULL REFERENCES mural.user(id),
    creation_date TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE USER webmural WITH PASSWORD '$up3r$3cr3t';

GRANT USAGE ON SCHEMA mural TO webmural;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mural TO webmural;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA mural TO webmural;
ALTER DEFAULT PRIVILEGES IN SCHEMA mural GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO webmural;
