version: '3'
services:
  sample_db:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8
